### ISSUE TITLE
flask db migrate doesn't work with flask-sqlalchemy 3.x

### ISSUE THREAD

**Issue by louking** [louking/mysql-docker#5]
related to #3

upgrade to flask-sqlalchemy-3.x, sqlalchemy-2.x

See https://github.com/miguelgrinberg/Flask-Migrate/discussions/521

**Comment by miguelgrinberg** [comment]
Flask-Migrate is a thin wrapper for Alembic, there is very little database-specific logic. Is there any chance this is actually a problem in your model definitions? It seems you are upgrading both SQLAlchemy and Flask-SQLAlchemy over major versions. Maybe something change there? Have you read the error message that you are getting? It seems to indicate there is a problem with your model definitions.
